package monster

import "github.com/zwh8800/cdnd/internal/character"

// Templates 预定义的怪物模板库
var Templates = map[string]*MonsterTemplate{
	// ========== CR 1/4 级别 ==========
	"goblin": {
		ID:        "goblin",
		Name:      "哥布林",
		Size:      SizeSmall,
		Type:      TypeHumanoid,
		Alignment: AlignmentNeutralEvil,
		CR:        0.25,
		XP:        50,
		HP:        "2d6",
		AC:        15,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     8,
			Dexterity:    14,
			Constitution: 10,
			Intelligence: 10,
			Wisdom:       8,
			Charisma:     8,
		},
		Skills: map[string]int{
			"隐匿": 6,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "哥布林语"},
		Actions: []MonsterAction{
			{
				Name:        "弯刀",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "短弓",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "穿刺",
				Range:       "80/320尺",
				Description: "远程武器攻击",
			},
		},
		Description: "哥布林是自私、狡猾且懦弱的小型人形生物，喜欢以多欺少。",
	},

	"skeleton": {
		ID:        "skeleton",
		Name:      "骷髅",
		Size:      SizeMedium,
		Type:      TypeUndead,
		Alignment: AlignmentLawfulEvil,
		CR:        0.25,
		XP:        50,
		HP:        "2d8+4",
		AC:        13,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     10,
			Dexterity:    14,
			Constitution: 15,
			Intelligence: 6,
			Wisdom:       8,
			Charisma:     5,
		},
		DamageImmunities:    []string{"毒素"},
		ConditionImmunities: []string{"中毒", "疲劳"},
		Senses:              []string{"黑暗视觉 60尺"},
		Languages:           []string{"生前所知的语言，但不能说话"},
		Actions: []MonsterAction{
			{
				Name:        "短剑",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "短弓",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "穿刺",
				Range:       "80/320尺",
				Description: "远程武器攻击",
			},
		},
		Description: "被死灵魔法唤醒的骸骨，服从创造者的命令。",
	},

	"zombie": {
		ID:        "zombie",
		Name:      "僵尸",
		Size:      SizeMedium,
		Type:      TypeUndead,
		Alignment: AlignmentNeutralEvil,
		CR:        0.25,
		XP:        50,
		HP:        "3d8+9",
		AC:        8,
		Speed:     20,
		Abilities: character.Attributes{
			Strength:     13,
			Dexterity:    6,
			Constitution: 16,
			Intelligence: 3,
			Wisdom:       6,
			Charisma:     5,
		},
		SavingThrows: map[string]int{
			"感知": 0,
		},
		DamageImmunities:    []string{"毒素"},
		ConditionImmunities: []string{"中毒", "疲劳"},
		Senses:              []string{"黑暗视觉 60尺"},
		Languages:           []string{"生前所知的语言，但不能说话"},
		Actions: []MonsterAction{
			{
				Name:        "猛击",
				Type:        ActionTypeMelee,
				AttackBonus: 3,
				Damage:      "1d6+1",
				DamageType:  "钝击",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
		},
		Description: "缓慢、无脑的不死生物，被对生者的饥饿驱使。",
	},

	"giant_rat": {
		ID:        "giant_rat",
		Name:      "巨鼠",
		Size:      SizeSmall,
		Type:      TypeBeast,
		Alignment: AlignmentUnaligned,
		CR:        0.125,
		XP:        25,
		HP:        "2d6",
		AC:        12,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     7,
			Dexterity:    15,
			Constitution: 11,
			Intelligence: 2,
			Wisdom:       10,
			Charisma:     4,
		},
		Skills: map[string]int{
			"察觉": 3,
		},
		Senses:    []string{"黑暗视觉 60尺", "灵敏嗅觉"},
		Languages: []string{},
		Actions: []MonsterAction{
			{
				Name:        "啃咬",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d4+2",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
		},
		Description: "体型如狗的巨型老鼠，通常成群出没。",
	},

	"kobold": {
		ID:        "kobold",
		Name:      "狗头人",
		Size:      SizeSmall,
		Type:      TypeHumanoid,
		Alignment: AlignmentLawfulEvil,
		CR:        0.125,
		XP:        25,
		HP:        "2d6-2",
		AC:        12,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     7,
			Dexterity:    15,
			Constitution: 9,
			Intelligence: 8,
			Wisdom:       7,
			Charisma:     8,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "龙语"},
		Actions: []MonsterAction{
			{
				Name:        "匕首",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d4+2",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "投石索",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d4+2",
				DamageType:  "钝击",
				Range:       "30/120尺",
				Description: "远程武器攻击",
			},
		},
		Description: "崇拜龙类的小型爬行生物，擅长陷阱和群体战术。",
	},

	// ========== CR 1/2 级别 ==========
	"bugbear": {
		ID:        "bugbear",
		Name:      "熊地精",
		Size:      SizeMedium,
		Type:      TypeHumanoid,
		Alignment: AlignmentChaoticEvil,
		CR:        0.5,
		XP:        100,
		HP:        "5d8+5",
		AC:        16,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     15,
			Dexterity:    14,
			Constitution: 13,
			Intelligence: 8,
			Wisdom:       11,
			Charisma:     9,
		},
		Skills: map[string]int{
			"隐匿": 6,
			"求生": 2,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "地精语"},
		Actions: []MonsterAction{
			{
				Name:        " morningstar",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "2d8+2",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击（ surprise attack: 额外2d6）",
			},
			{
				Name:        "标枪",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "穿刺",
				Range:       "30/120尺",
				Description: "远程武器攻击",
			},
		},
		Description: "体型庞大的地精类生物，擅长伏击和潜行。",
	},

	"goblin_boss": {
		ID:        "goblin_boss",
		Name:      "哥布林首领",
		Size:      SizeSmall,
		Type:      TypeHumanoid,
		Alignment: AlignmentNeutralEvil,
		CR:        0.5,
		XP:        100,
		HP:        "6d6+6",
		AC:        17,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     10,
			Dexterity:    14,
			Constitution: 12,
			Intelligence: 10,
			Wisdom:       8,
			Charisma:     10,
		},
		Skills: map[string]int{
			"隐匿": 6,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "哥布林语"},
		Actions: []MonsterAction{
			{
				Name:        "弯刀",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击（攻击后撤退不引发借机攻击）",
			},
			{
				Name:        "短弓",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d6+2",
				DamageType:  "穿刺",
				Range:       "80/320尺",
				Description: "远程武器攻击",
			},
		},
		Description: "比普通哥布林更强壮、更狡猾的领导者，指挥其他哥布林作战。",
	},

	"skeleton_warrior": {
		ID:        "skeleton_warrior",
		Name:      "骷髅战士",
		Size:      SizeMedium,
		Type:      TypeUndead,
		Alignment: AlignmentLawfulEvil,
		CR:        0.5,
		XP:        100,
		HP:        "4d8+8",
		AC:        15,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     14,
			Dexterity:    12,
			Constitution: 15,
			Intelligence: 6,
			Wisdom:       8,
			Charisma:     5,
		},
		DamageImmunities:    []string{"毒素"},
		ConditionImmunities: []string{"中毒", "疲劳"},
		Senses:              []string{"黑暗视觉 60尺"},
		Languages:           []string{},
		Actions: []MonsterAction{
			{
				Name:        "长剑",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "1d8+2",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "长弓",
				Type:        ActionTypeRanged,
				AttackBonus: 4,
				Damage:      "1d8+2",
				DamageType:  "穿刺",
				Range:       "150/600尺",
				Description: "远程武器攻击",
			},
		},
		Description: "装备精良武器的骷髅，比普通骷髅更具威胁。",
	},

	"dire_wolf": {
		ID:        "dire_wolf",
		Name:      "恐狼",
		Size:      SizeLarge,
		Type:      TypeBeast,
		Alignment: AlignmentUnaligned,
		CR:        0.5,
		XP:        100,
		HP:        "5d10+10",
		AC:        14,
		Speed:     50,
		Abilities: character.Attributes{
			Strength:     17,
			Dexterity:    15,
			Constitution: 15,
			Intelligence: 3,
			Wisdom:       12,
			Charisma:     7,
		},
		Skills: map[string]int{
			"察觉": 3,
			"隐匿": 4,
		},
		Senses:    []string{"黑暗视觉", "灵敏嗅觉"},
		Languages: []string{},
		Actions: []MonsterAction{
			{
				Name:        "啃咬",
				Type:        ActionTypeMelee,
				AttackBonus: 5,
				Damage:      "2d6+3",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击（如果目标被盟友包围则优势）",
			},
		},
		Description: "体型巨大的狼，通常成群狩猎。",
	},

	// ========== CR 1-2 级别 ==========
	"orc": {
		ID:        "orc",
		Name:      "兽人",
		Size:      SizeMedium,
		Type:      TypeHumanoid,
		Alignment: AlignmentChaoticEvil,
		CR:        1,
		XP:        200,
		HP:        "2d8+6",
		AC:        13,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     16,
			Dexterity:    12,
			Constitution: 16,
			Intelligence: 7,
			Wisdom:       11,
			Charisma:     10,
		},
		Skills: map[string]int{
			"威吓": 2,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "兽人语"},
		Actions: []MonsterAction{
			{
				Name:        "巨斧",
				Type:        ActionTypeMelee,
				AttackBonus: 5,
				Damage:      "1d12+3",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击（生命值低于一半时额外投一次伤害骰）",
			},
			{
				Name:        "标枪",
				Type:        ActionTypeRanged,
				AttackBonus: 5,
				Damage:      "1d6+3",
				DamageType:  "穿刺",
				Range:       "30/120尺",
				Description: "远程武器攻击",
			},
		},
		Description: "野蛮好战的类人生物，崇尚力量和征服。",
	},

	"ogre": {
		ID:        "ogre",
		Name:      "食人魔",
		Size:      SizeLarge,
		Type:      TypeGiant,
		Alignment: AlignmentChaoticEvil,
		CR:        2,
		XP:        450,
		HP:        "7d10+21",
		AC:        11,
		Speed:     40,
		Abilities: character.Attributes{
			Strength:     19,
			Dexterity:    8,
			Constitution: 16,
			Intelligence: 5,
			Wisdom:       7,
			Charisma:     7,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"通用语", "巨人语"},
		Actions: []MonsterAction{
			{
				Name:        "大棒",
				Type:        ActionTypeMelee,
				AttackBonus: 6,
				Damage:      "2d8+4",
				DamageType:  "钝击",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
		},
		Description: "体型庞大、智力低下的巨人，以暴力闻名。",
	},

	"ghoul": {
		ID:        "ghoul",
		Name:      "食尸鬼",
		Size:      SizeMedium,
		Type:      TypeUndead,
		Alignment: AlignmentChaoticEvil,
		CR:        1,
		XP:        200,
		HP:        "5d8",
		AC:        12,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     13,
			Dexterity:    15,
			Constitution: 10,
			Intelligence: 7,
			Wisdom:       10,
			Charisma:     6,
		},
		DamageImmunities:    []string{"毒素"},
		ConditionImmunities: []string{"魅惑", "中毒", "疲劳"},
		Senses:              []string{"黑暗视觉 60尺"},
		Languages:           []string{"通用语"},
		Actions: []MonsterAction{
			{
				Name:        "啃咬",
				Type:        ActionTypeMelee,
				AttackBonus: 2,
				Damage:      "2d6+1",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击（命中后目标需体质豁免DC10，否则麻痹）",
			},
			{
				Name:        "爪击",
				Type:        ActionTypeMelee,
				AttackBonus: 4,
				Damage:      "2d4+1",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击（命中后目标需体质豁免DC10，否则麻痹）",
			},
		},
		Description: "以尸体为食的不死生物，对生者充满饥渴。",
	},

	// ========== CR 3-5 级别 ==========
	"troll": {
		ID:        "troll",
		Name:      "巨魔",
		Size:      SizeLarge,
		Type:      TypeGiant,
		Alignment: AlignmentChaoticEvil,
		CR:        5,
		XP:        1800,
		HP:        "8d10+40",
		AC:        15,
		Speed:     30,
		Abilities: character.Attributes{
			Strength:     18,
			Dexterity:    13,
			Constitution: 20,
			Intelligence: 7,
			Wisdom:       9,
			Charisma:     7,
		},
		Skills: map[string]int{
			"察觉": 2,
		},
		Senses:    []string{"黑暗视觉 60尺"},
		Languages: []string{"巨人语"},
		Actions: []MonsterAction{
			{
				Name:        "啃咬",
				Type:        ActionTypeMelee,
				AttackBonus: 7,
				Damage:      "1d6+4",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "爪击",
				Type:        ActionTypeMelee,
				AttackBonus: 7,
				Damage:      "2d6+4",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击（每次回合可进行两次爪击）",
			},
		},
		Description: "具有惊人再生能力的巨人，除非受到火焰或强酸伤害，否则难以杀死。",
		DMNotes:     "每回合开始时恢复10点生命值，除非受到火焰或强酸伤害。",
	},

	"owlbear": {
		ID:        "owlbear",
		Name:      "枭熊",
		Size:      SizeLarge,
		Type:      TypeMonstrosity,
		Alignment: AlignmentUnaligned,
		CR:        3,
		XP:        700,
		HP:        "7d10+21",
		AC:        13,
		Speed:     40,
		Abilities: character.Attributes{
			Strength:     20,
			Dexterity:    12,
			Constitution: 17,
			Intelligence: 3,
			Wisdom:       12,
			Charisma:     7,
		},
		Skills: map[string]int{
			"察觉": 3,
		},
		Senses:    []string{"黑暗视觉 60尺", "灵敏嗅觉"},
		Languages: []string{},
		Actions: []MonsterAction{
			{
				Name:        "喙啄",
				Type:        ActionTypeMelee,
				AttackBonus: 7,
				Damage:      "1d10+5",
				DamageType:  "穿刺",
				Range:       "5尺",
				Description: "近战武器攻击",
			},
			{
				Name:        "爪击",
				Type:        ActionTypeMelee,
				AttackBonus: 7,
				Damage:      "2d8+5",
				DamageType:  "挥砍",
				Range:       "5尺",
				Description: "近战武器攻击（如果喙啄命中则优势）",
			},
		},
		Description: "熊的身体配上猫头鹰的头部，领地意识极强的凶猛生物。",
	},

	"wraith": {
		ID:        "wraith",
		Name:      "幽灵",
		Size:      SizeMedium,
		Type:      TypeUndead,
		Alignment: AlignmentNeutralEvil,
		CR:        5,
		XP:        1800,
		HP:        "9d8+27",
		AC:        13,
		Speed:     0,
		Abilities: character.Attributes{
			Strength:     6,
			Dexterity:    16,
			Constitution: 16,
			Intelligence: 12,
			Wisdom:       14,
			Charisma:     15,
		},
		Skills: map[string]int{
			"察觉": 4,
		},
		DamageResistances:   []string{"强酸", "冷冻", "火焰", "闪电", "雷鸣", "非魔法武器的钝击/穿刺/挥砍"},
		DamageImmunities:    []string{"亡灵", "毒素"},
		ConditionImmunities: []string{"魅惑", "擒抱", "麻痹", "石化", "倒地", "束缚", "疲劳", "中毒", "昏迷"},
		Senses:              []string{"黑暗视觉 60尺"},
		Languages:           []string{"通用语", "生前所知的语言"},
		Actions: []MonsterAction{
			{
				Name:        "生命吸取",
				Type:        ActionTypeMelee,
				AttackBonus: 6,
				Damage:      "4d8+3",
				DamageType:  "黯蚀",
				Range:       "5尺",
				Description: "近战法术攻击（目标需体质豁免DC14，否则生命值上限减少伤害值）",
			},
		},
		Description: "由强烈怨恨形成的不死灵体，能够穿墙而过，吸取生命。",
	},
}

// GetTemplate 获取怪物模板
func GetTemplate(id string) (*MonsterTemplate, bool) {
	template, ok := Templates[id]
	if !ok {
		return nil, false
	}
	// 返回副本以防止修改原始模板
	copy := *template
	return &copy, true
}

// GetTemplatesByCR 获取指定CR范围内的所有模板
func GetTemplatesByCR(minCR, maxCR float64) []*MonsterTemplate {
	var result []*MonsterTemplate
	for _, template := range Templates {
		if template.CR >= minCR && template.CR <= maxCR {
			copy := *template
			result = append(result, &copy)
		}
	}
	return result
}

// GetAllTemplateIDs 获取所有模板ID
func GetAllTemplateIDs() []string {
	var ids []string
	for id := range Templates {
		ids = append(ids, id)
	}
	return ids
}
